sudo: false
dist: trusty
language: node_js
node_js:
  - '6'

cache:
  yarn: true
  directories:
    - node_modules

install:
- yarn install

before_deploy:
- $(yarn bin)/gulp
- echo 'teiler.io' > dist/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
